Crowdfund_TeamProject.Web/Controllers/BackerController.cs
using Crowdfund_TeamProject.Core.Model;
using Crowdfund_TeamProject.Services;
using Crowdfund_TeamProject.Web.Extensions;
using Crowdfund_TeamProject.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Crowdfund_TeamProject.Web.Controllers
{
    public class BackerController : Controller
    {
        private readonly IBackerService bksrv_;
        private readonly Data.Crowdfund_TeamProjectDbContext context_;

        public BackerController(
         IBackerService bksrv,
         Data.Crowdfund_TeamProjectDbContext context)
        {
            bksrv_ = bksrv;
            context_ = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Create(
           [FromBody] Core.Model.Options.AddBackerOptions options)
        {
            var result = await bksrv_
                .AddBackerAsync(options);
                
            return result.AsStatusResult();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DashBoard()
        {
            var backer = await bksrv_
                .GetBackerByIdAsync(1);

            var projlist = context_
                .Set<Project>()
                .Where(p => p.Creator.Id == 1)
                .ToList();

            var model = new BackerProjectViewModel()
            {
                Backer = backer.Data,
                ProjectList = projlist
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddTier([FromBody] BackerAddProjectViewModel options)
        {
            var result = await bksrv_.SelectProjectAsync(1, options.ProjectId, options.Amount);
            return Ok();
        }
    }
}

Crowdfund_TeamProject.Web/Controllers/CreatorController.cs
using Crowdfund_TeamProject.Core.Model;
using Crowdfund_TeamProject.Services;
using Crowdfund_TeamProject.Web.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Crowdfund_TeamProject.Web.Controllers
{
    public class CreatorController : Controller
    {
        private readonly ICreatorService crsrv_;
        private readonly Data.Crowdfund_TeamProjectDbContext context_;

        public CreatorController(
            ICreatorService crsrv,
            Data.Crowdfund_TeamProjectDbContext context)
        {
            crsrv_ = crsrv;
            context_ = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(
            [FromBody] Core.Model.Options.AddCreatorOptions options)
        {
            var result = await crsrv_
                .AddCreatorAsync(options);

            return result.AsStatusResult();

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DashBoard()
        {
            var projlist = context_
                .Set<Project>()
                .Where(p => p.Creator.Id == 1)
                .ToList();

            var creator = await crsrv_
                .GetCreatorByIdAsync(1);

            var model = new Models.CreatorProjectViewModel()
            {
                Creator = creator.Data,
                ProjectList = projlist
            };

            return View(model);
        }
    }
}

Crowdfund_TeamProject.Web/Controllers/ProjectController.cs
using Crowdfund_TeamProject.Core.Model;
using Crowdfund_TeamProject.Core.Model.Options;
using Crowdfund_TeamProject.Core.Services;
using Crowdfund_TeamProject.Services;
using Crowdfund_TeamProject.Web.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Crowdfund_TeamProject.Web.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService project_;
        private readonly IUpdatePostService updsrv_;
        private readonly Data.Crowdfund_TeamProjectDbContext context_;

        public ProjectController(
            IProjectService project,
            IUpdatePostService updsrv,
            Data.Crowdfund_TeamProjectDbContext context)
        {   
            context_ = context;
            project_ = project;
            updsrv_ = updsrv;
        }

        public IActionResult Index()
        {
            var resultList = context_
                .Set<Project>().ToList();

            return View("List",resultList);
        }

        [HttpGet("project/{id}")]
        public async Task<IActionResult> Details(
           int id)
        {
            var result = await project_
                .SearchProjectByIdAaync(id);
            if(result.ErrorCode == Core.StatusCode.OK) {
                return View(result.Data);
            }

            return result.AsStatusResult();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] AddProjectOptions options)
        {            
            var result = await project_.CreateProjectAsync(1, options);
            
            if (result.ErrorCode == Core.StatusCode.OK){
                return Ok(result.Data);
            }
            
            return result.AsStatusResult();
        }

        public IActionResult SearchProject( )
        {
            var resultList = context_
                .Set<Project>()
                .Take(100)
                .ToList();

            return View(resultList);
        }

        [HttpPost]
        public IActionResult Search(
           [FromBody] SearchProjectOptions options)
        {
            if (options.Category == ProjectCategory.Invalid) {
                return BadRequest("Project Category is required");
            }

            var resultList = project_.SearchProject(
                new SearchProjectOptions()
                {
                    Category = options.Category
                })
                .Select(r => new { r.Category, r.Creator, r.Title, r.Goal, r.ExpirationDate })
                .Take(100)
                .ToList();

            return Json(resultList);
        }
    }
}

Crowdfund_TeamProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crowdfund_TeamProject.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrowdFund</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Creator" asp-action="Dashboard">Creator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Backer" asp-action="Dashboard">Backer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Create">Project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="SearchProject">Search Project</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Crowdfund_TeamProject.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>